name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - t=${{ matrix.threads }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux runner configurations
          - os: ubuntu-latest
            arch: x64
            threads: '5'
            julia-version: '1'

          # Windows runner configurations
          - os: windows-latest
            arch: x64
            threads: '5'
            julia-version: '1'
          
          # Native Apple Silicon configurations
          - os: macOS-latest
            arch: aarch64
            threads: '5'
            julia-version: '1'
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v3

      - name: Resolve Manifest
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.add("General") 

          # Delete the committed Manifest.toml so a valid one can be generated
          if isfile("Manifest.toml")
            rm("Manifest.toml")
          end

          Pkg.activate(".")
          Pkg.resolve()
          Pkg.instantiate()

      - uses: julia-actions/julia-buildpkg@v1

      - uses: julia-actions/julia-runtest@v1
        env:
          JULIA_NUM_THREADS: ${{ matrix.threads }}
          PTR_NUM_JOBS: ${{ matrix.threads }}
        with:
          coverage: true

      - uses: julia-actions/julia-processcoverage@v1
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info


